"""empty message

Revision ID: 62b1ee5054f3
Revises: fce230d523b5
Create Date: 2025-12-05 22:40:04.681884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62b1ee5054f3'
down_revision = 'fce230d523b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('media_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['type'])
        batch_op.create_unique_constraint(None, ['url'])
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.drop_column('is_active')
        batch_op.drop_column('email')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('media_email_key', ['email'])
        batch_op.drop_column('post_id')
        batch_op.drop_column('url')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
